### ISSUE TITLE
Тип персони по замовчення

### ISSUE THREAD

**Issue by illay1994** [ITsvetkoFF/Kv-007.LNU#130]
Додати при створенні персони 
Абітурієнт - тип персони по замовченням
![2015-05-17 14 34 50](https://cloud.githubusercontent.com/assets/10198202/7670149/0b5a824c-fca2-11e4-8a56-82fbb3405868.png)

**Comment by Tetyana-Che** [comment]
добавила тип персоны "абитуриент" по умолчанию
