### ISSUE TITLE
Додавання ЗНО

### ISSUE THREAD

**Issue by illay1994** [ITsvetkoFF/Kv-007.LNU#131]
При додаваня ЗНО у документи персони не потрібно поля середній бал
Якщо у документах персони немає ЗНО то таба Предмети ЗНО має бути неактивною.
![2015-05-17 14 47 27](https://cloud.githubusercontent.com/assets/10198202/7670197/d1b87bd2-fca3-11e4-8d63-f6d0bbbdd106.png)

**Comment by Tetyana-Che** [comment]
убрала средний бал при добавлении сертификата ЗНО
