### ISSUE TITLE
баг при редагуванні персони

### ISSUE THREAD

**Issue by illay1994** [ITsvetkoFF/Kv-007.LNU#138]
![2015-05-17 15 15 58](https://cloud.githubusercontent.com/assets/10198202/7670293/df10f684-fca7-11e4-8458-f40035e5f3c7.png)

**Comment by Tetyana-Che** [comment]
Большинство персон вначале списка добавлены через постмен и не имеют адресов, поэтому не будут корректно отображаться. Персоны, которые добавлены вручную с UI должны иметь адреса, тогда все будет отображаться и редактироваться правильно.
